name: Terraform Deployment Workflow
# This workflow sets up a Terraform deployment pipeline using GitHub Actions.
# It includes steps for checking Terraform code formatting, generating a plan,
# and applying the plan to AWS infrastructure using OIDC for authentication.

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  id-token: write   # Allows requesting an OIDC token
  contents: read    # Required for actions/checkout

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Format Terraform code
        run: terraform fmt -check

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Generate Terraform Plan
        run: terraform plan -out=tf.plan

      - name: Upload Terraform Plan for Terraform Apply
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: tf.plan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Download Terraform Plan from Previous Job
        uses: actions/download-artifact@v4
        with:
          name: tf-plan

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve tf.plan